services:
  # A Docker web service
  - type: web
    name: simian-web-app
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    buildFilter:
      ignoredPaths:
        - README.md
        - readme-images/*
        - .gitignore